[openai]
api_key = "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"

[ncbi]
base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"

[springer]
api_key = "fff711650fcd0bdaef7a15cdd573e4fb"
base_url = "https://api.springernature.com/meta/v2/json"

[assistant]
id = "asst_fEbBTAziC93bXGhVbIbbUQ5V"
thread_id = "thread_MyngT1Kbthb0wv49ov1U1o86"

[literal]
api_key = "lsk_NiCW8sfs0HTtuBv88Uf9phzjxDhg2dfINgEtfjSXVxw"

[core]
api_key = "Hr9d5yJX8iG3kDwYVWKZqvR6zOfoaNM0"
base_url = "https://api.core.ac.uk/v3"

[sciencedirect]
api_key = "379380bfd2b94b67078a942f06f132ba"
base_url = "https://api.elsevier.com/content/metadata/article"
